//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptionist.Services.CallOutcomeSubmission
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallOutcomeContext : DbContext
    {
        public CallOutcomeContext()
            : base("name=CallOutcomeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Call> T_Call { get; set; }
        public DbSet<T_LeadVendorEmailHeader> T_LeadVendorEmailHeader { get; set; }
        public DbSet<T_MollyMaidCallOutcome> T_MollyMaidCallOutcome { get; set; }
        public DbSet<T_CallNeed> T_CallNeed { get; set; }
        public DbSet<T_L_Need> T_L_Need { get; set; }
        public DbSet<T_L_Outcome> T_L_Outcome { get; set; }
        public DbSet<T_L_NeedField> T_L_NeedField { get; set; }
        public DbSet<T_Company> T_Company { get; set; }
    }
}
