//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptionist.Services.CallOutcomeSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Call
    {
        public T_Call()
        {
            this.T_MollyMaidCallOutcome = new HashSet<T_MollyMaidCallOutcome>();
            this.T_CallNeed = new HashSet<T_CallNeed>();
        }
    
        public int CallID { get; set; }
        public string DID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CallerID { get; set; }
        public string CallerPhoneNumber { get; set; }
        public string CallerName { get; set; }
        public string CallerCompany { get; set; }
        public Nullable<int> CallerRelationshipID { get; set; }
        public Nullable<int> NeedID { get; set; }
        public Nullable<int> OutcomeID { get; set; }
        public Nullable<int> CallDispositionID { get; set; }
        public string Message { get; set; }
        public Nullable<int> TVCallID { get; set; }
        public Nullable<bool> Billable { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string EnteredBy { get; set; }
        public byte[] Concurrency { get; set; }
        public string PerceptionistID { get; set; }
        public string Db2ID { get; set; }
        public Nullable<System.DateTime> DisconnectedOn { get; set; }
        public Nullable<byte> CallDirection { get; set; }
        public string CallActions { get; set; }
        public Nullable<int> CallLogID { get; set; }
        public Nullable<int> CallCampaignDetailID { get; set; }
        public string AudioFilename { get; set; }
    
        public virtual ICollection<T_MollyMaidCallOutcome> T_MollyMaidCallOutcome { get; set; }
        public virtual T_L_Need T_L_Need { get; set; }
        public virtual ICollection<T_CallNeed> T_CallNeed { get; set; }
        public virtual T_L_Outcome T_L_Outcome { get; set; }
        public virtual T_Company T_Company { get; set; }
    }
}
