//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptionist.Services.CallOutcomeSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Company
    {
        public T_Company()
        {
            this.T_Call = new HashSet<T_Call>();
        }
    
        public int CompanyID { get; set; }
        public string Company { get; set; }
        public string DisplayAs { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public string AccountMgr { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<bool> AdjustForDaylightSavings { get; set; }
        public string Bio { get; set; }
        public string DrivingInstructions { get; set; }
        public string Phone_Notes { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string EnteredBy { get; set; }
        public byte[] Concurrency { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public string SvcAgreementHTML { get; set; }
        public Nullable<System.DateTime> SvcAgreementDate { get; set; }
        public Nullable<System.DateTime> ServiceCancelledOn { get; set; }
        public string ServiceCancelledBy { get; set; }
        public string Telco_Name { get; set; }
        public string Telco_RepairContact { get; set; }
        public string Telco_RepairPhone { get; set; }
        public string Telco_CustSvcPhone { get; set; }
        public string Telco_SecurityInfo { get; set; }
        public string Phone_AA_Ext { get; set; }
        public string Phone_UserExt { get; set; }
        public string Phone_AfterHrsCallsGoTo { get; set; }
        public Nullable<bool> Phone_IVR_Notification { get; set; }
        public string Phone_IVR_SentNoticeTo { get; set; }
        public string BillTo_Company { get; set; }
        public string BillTo_Address1 { get; set; }
        public string BillTo_Address2 { get; set; }
        public string BillTo_Address3 { get; set; }
        public string BillTo_City { get; set; }
        public string BillTo_State { get; set; }
        public string BillTo_Zip { get; set; }
        public string BillTo_Phone { get; set; }
        public string BillTo_Fax { get; set; }
        public string BillTo_Contact { get; set; }
        public string BillTo_ContactEmail { get; set; }
        public Nullable<bool> IncludeInSalesStats { get; set; }
        public string BillTo_PricingInfo { get; set; }
        public Nullable<bool> CC_RequireSecurityCode { get; set; }
        public string CC_CardsAccepted { get; set; }
        public Nullable<bool> Invoice_Consolidated { get; set; }
        public Nullable<int> Invoice_ParentCompanyID { get; set; }
        public Nullable<System.DateTime> ServiceActivatedOn { get; set; }
        public Nullable<System.DateTime> ServiceSuspendedOn { get; set; }
        public Nullable<System.DateTime> PilotProgramEndedOn { get; set; }
        public Nullable<int> ZorID { get; set; }
        public Nullable<System.DateTime> WaveAcctMgtFeeStartOn { get; set; }
        public Nullable<System.DateTime> WaveAcctMgtFeeEndOn { get; set; }
        public Nullable<int> AcctMgtFeeTypeID { get; set; }
        public Nullable<int> BusinessUnitID { get; set; }
        public Nullable<int> ProductLineID { get; set; }
        public Nullable<int> SalesRepID { get; set; }
        public string FranchiseID { get; set; }
        public Nullable<bool> AllowImmediateRecordingAccess { get; set; }
        public bool RemoveFromNoSale { get; set; }
    
        public virtual ICollection<T_Call> T_Call { get; set; }
    }
}
