//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptionist.Services.CallOutcomeSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_L_Outcome
    {
        public T_L_Outcome()
        {
            this.T_Call = new HashSet<T_Call>();
        }
    
        public int OutcomeID { get; set; }
        public string Outcome { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string EnteredBy { get; set; }
        public byte[] Concurrency { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> CCDetailStatusID { get; set; }
    
        public virtual ICollection<T_Call> T_Call { get; set; }
    }
}
