//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptionist.Services.CallOutcomeSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_L_Need
    {
        public T_L_Need()
        {
            this.T_Call = new HashSet<T_Call>();
            this.T_CallNeed = new HashSet<T_CallNeed>();
            this.T_L_NeedField = new HashSet<T_L_NeedField>();
        }
    
        public int NeedID { get; set; }
        public string Need { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string EnteredBy { get; set; }
        public byte[] Concurrency { get; set; }
        public string GroupBy { get; set; }
        public Nullable<bool> IsCalendarNeed { get; set; }
        public Nullable<bool> IsFAQ { get; set; }
        public Nullable<byte> CalendarAction { get; set; }
        public string BillingTypeID { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual ICollection<T_Call> T_Call { get; set; }
        public virtual ICollection<T_CallNeed> T_CallNeed { get; set; }
        public virtual ICollection<T_L_NeedField> T_L_NeedField { get; set; }
    }
}
