//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptionist.Services.CallOutcomeSubmission
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LeadVendorEmailHeader
    {
        public T_LeadVendorEmailHeader()
        {
            this.T_MollyMaidCallOutcome = new HashSet<T_MollyMaidCallOutcome>();
        }
    
        public int LeadVendorEmailID { get; set; }
        public int LeadVendorAccountID { get; set; }
        public string email_from { get; set; }
        public string email_to { get; set; }
        public string email_date { get; set; }
        public string email_subject { get; set; }
        public string email_text { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> CallbackOn { get; set; }
        public string FranchiseNumber { get; set; }
        public byte RemoveFromList { get; set; }
    
        public virtual ICollection<T_MollyMaidCallOutcome> T_MollyMaidCallOutcome { get; set; }
    }
}
