//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perceptionist.Services.CallOutcomeSubmission.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadableDataObject", Namespace="http://schemas.datacontract.org/2004/07/SbiLib.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LeadDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Perceptionist.Services.CallOutcomeSubmission.ServiceReference.ListItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Franchise))]
    public partial class LoadableDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeadDetail", Namespace="http://schemas.datacontract.org/2004/07/SBI.MollyMaid.PerceptionistAPI.Service")]
    [System.SerializableAttribute()]
    public partial class LeadDetail : Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LoadableDataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BathroomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BedroomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LeadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NationalLeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone3TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SquareFeetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bathrooms {
            get {
                return this.BathroomsField;
            }
            set {
                if ((object.ReferenceEquals(this.BathroomsField, value) != true)) {
                    this.BathroomsField = value;
                    this.RaisePropertyChanged("Bathrooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bedrooms {
            get {
                return this.BedroomsField;
            }
            set {
                if ((object.ReferenceEquals(this.BedroomsField, value) != true)) {
                    this.BedroomsField = value;
                    this.RaisePropertyChanged("Bedrooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTime {
            get {
                return this.ContactTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactTimeField, value) != true)) {
                    this.ContactTimeField = value;
                    this.RaisePropertyChanged("ContactTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranNum {
            get {
                return this.FranNumField;
            }
            set {
                if ((this.FranNumField.Equals(value) != true)) {
                    this.FranNumField = value;
                    this.RaisePropertyChanged("FranNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((object.ReferenceEquals(this.FrequencyField, value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LeadDate {
            get {
                return this.LeadDateField;
            }
            set {
                if ((this.LeadDateField.Equals(value) != true)) {
                    this.LeadDateField = value;
                    this.RaisePropertyChanged("LeadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeadId {
            get {
                return this.LeadIdField;
            }
            set {
                if ((this.LeadIdField.Equals(value) != true)) {
                    this.LeadIdField = value;
                    this.RaisePropertyChanged("LeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadSource {
            get {
                return this.LeadSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadSourceField, value) != true)) {
                    this.LeadSourceField = value;
                    this.RaisePropertyChanged("LeadSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadStatus {
            get {
                return this.LeadStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadStatusField, value) != true)) {
                    this.LeadStatusField = value;
                    this.RaisePropertyChanged("LeadStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NationalLeadId {
            get {
                return this.NationalLeadIdField;
            }
            set {
                if ((this.NationalLeadIdField.Equals(value) != true)) {
                    this.NationalLeadIdField = value;
                    this.RaisePropertyChanged("NationalLeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextAction {
            get {
                return this.NextActionField;
            }
            set {
                if ((object.ReferenceEquals(this.NextActionField, value) != true)) {
                    this.NextActionField = value;
                    this.RaisePropertyChanged("NextAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pets {
            get {
                return this.PetsField;
            }
            set {
                if ((object.ReferenceEquals(this.PetsField, value) != true)) {
                    this.PetsField = value;
                    this.RaisePropertyChanged("Pets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1Type {
            get {
                return this.Phone1TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1TypeField, value) != true)) {
                    this.Phone1TypeField = value;
                    this.RaisePropertyChanged("Phone1Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2Type {
            get {
                return this.Phone2TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2TypeField, value) != true)) {
                    this.Phone2TypeField = value;
                    this.RaisePropertyChanged("Phone2Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone3 {
            get {
                return this.Phone3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone3Field, value) != true)) {
                    this.Phone3Field = value;
                    this.RaisePropertyChanged("Phone3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone3Type {
            get {
                return this.Phone3TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Phone3TypeField, value) != true)) {
                    this.Phone3TypeField = value;
                    this.RaisePropertyChanged("Phone3Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SquareFeet {
            get {
                return this.SquareFeetField;
            }
            set {
                if ((object.ReferenceEquals(this.SquareFeetField, value) != true)) {
                    this.SquareFeetField = value;
                    this.RaisePropertyChanged("SquareFeet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListItem", Namespace="http://schemas.datacontract.org/2004/07/SBI.MollyMaid.PerceptionistAPI.Service")]
    [System.SerializableAttribute()]
    public partial class ListItem : Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LoadableDataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Franchise", Namespace="http://schemas.datacontract.org/2004/07/SBI.MollyMaid.PerceptionistAPI.Service")]
    [System.SerializableAttribute()]
    public partial class Franchise : Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LoadableDataObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranchiseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PerceptionistIntegrationEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PerceptionistLeadPushActivationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PerceptionistLeadPushEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBA {
            get {
                return this.DBAField;
            }
            set {
                if ((object.ReferenceEquals(this.DBAField, value) != true)) {
                    this.DBAField = value;
                    this.RaisePropertyChanged("DBA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranNum {
            get {
                return this.FranNumField;
            }
            set {
                if ((this.FranNumField.Equals(value) != true)) {
                    this.FranNumField = value;
                    this.RaisePropertyChanged("FranNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranchiseId {
            get {
                return this.FranchiseIdField;
            }
            set {
                if ((this.FranchiseIdField.Equals(value) != true)) {
                    this.FranchiseIdField = value;
                    this.RaisePropertyChanged("FranchiseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PerceptionistIntegrationEnabled {
            get {
                return this.PerceptionistIntegrationEnabledField;
            }
            set {
                if ((this.PerceptionistIntegrationEnabledField.Equals(value) != true)) {
                    this.PerceptionistIntegrationEnabledField = value;
                    this.RaisePropertyChanged("PerceptionistIntegrationEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PerceptionistLeadPushActivationDate {
            get {
                return this.PerceptionistLeadPushActivationDateField;
            }
            set {
                if ((this.PerceptionistLeadPushActivationDateField.Equals(value) != true)) {
                    this.PerceptionistLeadPushActivationDateField = value;
                    this.RaisePropertyChanged("PerceptionistLeadPushActivationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PerceptionistLeadPushEnabled {
            get {
                return this.PerceptionistLeadPushEnabledField;
            }
            set {
                if ((this.PerceptionistLeadPushEnabledField.Equals(value) != true)) {
                    this.PerceptionistLeadPushEnabledField = value;
                    this.RaisePropertyChanged("PerceptionistLeadPushEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortName {
            get {
                return this.SortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SortNameField, value) != true)) {
                    this.SortNameField = value;
                    this.RaisePropertyChanged("SortName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lead", Namespace="http://schemas.datacontract.org/2004/07/SBI.MollyMaid.PerceptionistAPI.Service")]
    [System.SerializableAttribute()]
    public partial class Lead : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LeadAction LeadActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LeadDetail LeadDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranNum {
            get {
                return this.FranNumField;
            }
            set {
                if ((this.FranNumField.Equals(value) != true)) {
                    this.FranNumField = value;
                    this.RaisePropertyChanged("FranNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LeadAction LeadAction {
            get {
                return this.LeadActionField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadActionField, value) != true)) {
                    this.LeadActionField = value;
                    this.RaisePropertyChanged("LeadAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LeadDetail LeadDetails {
            get {
                return this.LeadDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadDetailsField, value) != true)) {
                    this.LeadDetailsField = value;
                    this.RaisePropertyChanged("LeadDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeadAction", Namespace="http://schemas.datacontract.org/2004/07/SBI.MollyMaid.PerceptionistAPI.Service")]
    [System.SerializableAttribute()]
    public partial class LeadAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ActionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeadActionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Outcome OutcomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDate {
            get {
                return this.ActionDateField;
            }
            set {
                if ((this.ActionDateField.Equals(value) != true)) {
                    this.ActionDateField = value;
                    this.RaisePropertyChanged("ActionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTypeField, value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeadActionId {
            get {
                return this.LeadActionIdField;
            }
            set {
                if ((this.LeadActionIdField.Equals(value) != true)) {
                    this.LeadActionIdField = value;
                    this.RaisePropertyChanged("LeadActionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Outcome Outcome {
            get {
                return this.OutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeField, value) != true)) {
                    this.OutcomeField = value;
                    this.RaisePropertyChanged("Outcome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Outcome", Namespace="http://schemas.datacontract.org/2004/07/SBI.MollyMaid.PerceptionistAPI.Service")]
    [System.SerializableAttribute()]
    public partial class Outcome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallOutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailedCallOutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeedTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalNotes {
            get {
                return this.AdditionalNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalNotesField, value) != true)) {
                    this.AdditionalNotesField = value;
                    this.RaisePropertyChanged("AdditionalNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallOutcome {
            get {
                return this.CallOutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CallOutcomeField, value) != true)) {
                    this.CallOutcomeField = value;
                    this.RaisePropertyChanged("CallOutcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailedCallOutcome {
            get {
                return this.DetailedCallOutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailedCallOutcomeField, value) != true)) {
                    this.DetailedCallOutcomeField = value;
                    this.RaisePropertyChanged("DetailedCallOutcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NeedType {
            get {
                return this.NeedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NeedTypeField, value) != true)) {
                    this.NeedTypeField = value;
                    this.RaisePropertyChanged("NeedType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ILeadService")]
    public interface ILeadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/GetFranchiseDetails", ReplyAction="http://tempuri.org/ILeadService/GetFranchiseDetailsResponse")]
        Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Franchise GetFranchiseDetails(int franNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/FranchiseExists", ReplyAction="http://tempuri.org/ILeadService/FranchiseExistsResponse")]
        bool FranchiseExists(int franNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/GetLeadDetails", ReplyAction="http://tempuri.org/ILeadService/GetLeadDetailsResponse")]
        Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Lead GetLeadDetails(int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/GetLookupList", ReplyAction="http://tempuri.org/ILeadService/GetLookupListResponse")]
        Perceptionist.Services.CallOutcomeSubmission.ServiceReference.ListItem[] GetLookupList(string listName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/SubmitLead", ReplyAction="http://tempuri.org/ILeadService/SubmitLeadResponse")]
        System.Nullable<int> SubmitLead(Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Lead lead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/SubmitLeadAction", ReplyAction="http://tempuri.org/ILeadService/SubmitLeadActionResponse")]
        System.Nullable<int> SubmitLeadAction(int leadId, Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LeadAction leadAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/SubmitLeadOutcome", ReplyAction="http://tempuri.org/ILeadService/SubmitLeadOutcomeResponse")]
        System.Nullable<int> SubmitLeadOutcome(int leadId, Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Outcome outcome);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeadServiceChannel : Perceptionist.Services.CallOutcomeSubmission.ServiceReference.ILeadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeadServiceClient : System.ServiceModel.ClientBase<Perceptionist.Services.CallOutcomeSubmission.ServiceReference.ILeadService>, Perceptionist.Services.CallOutcomeSubmission.ServiceReference.ILeadService {
        
        public LeadServiceClient() {
        }
        
        public LeadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Franchise GetFranchiseDetails(int franNum) {
            return base.Channel.GetFranchiseDetails(franNum);
        }
        
        public bool FranchiseExists(int franNum) {
            return base.Channel.FranchiseExists(franNum);
        }
        
        public Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Lead GetLeadDetails(int leadId) {
            return base.Channel.GetLeadDetails(leadId);
        }
        
        public Perceptionist.Services.CallOutcomeSubmission.ServiceReference.ListItem[] GetLookupList(string listName) {
            return base.Channel.GetLookupList(listName);
        }
        
        public System.Nullable<int> SubmitLead(Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Lead lead) {
            return base.Channel.SubmitLead(lead);
        }
        
        public System.Nullable<int> SubmitLeadAction(int leadId, Perceptionist.Services.CallOutcomeSubmission.ServiceReference.LeadAction leadAction) {
            return base.Channel.SubmitLeadAction(leadId, leadAction);
        }
        
        public System.Nullable<int> SubmitLeadOutcome(int leadId, Perceptionist.Services.CallOutcomeSubmission.ServiceReference.Outcome outcome) {
            return base.Channel.SubmitLeadOutcome(leadId, outcome);
        }
    }
}
